apiVersion: v2
name: client
description: A Helm chart for Kubernetes

type: application
version: 1.0.3
appVersion: "1.0.3"

dependencies:
  - name: services
    version: 1.0.1
    condition: services.enabled
    repository: file://charts/services
  - name: workers
    version: 1.0.1
    condition: workers.enabled
    repository: file://charts/workers

  - name: assets
    version: 1.0.0
    condition: assets.enabled
    repository: file://charts/assets

  - name: frontend
    version: 1.0.2
    condition: frontend.enabled
    repository: file://charts/frontend

icon: https://artifacthub.io/image/8dee5d2f-5946-4fb5-b0a8-265ff014cdc1@1x
