replicaCount: 3

fullnameOverride: "client-gateway"

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 80
  targetPort: 6010

ingress:
  enabled: false

autoscaling:
  enabled: false

global:
  image:
    repository: wenex/client
    pullPolicy: IfNotPresent
    tag: "1.1.0"
  # **********************
  # Secrets
  # **********************
  secrets:
    init:
      phc:
        rootPassword: "" # default: random 40 chars
        clientSecret: "" # default: random 40 chars
    aes: "" # default: random 64 chars
    altcha:
      hmacKey: "" # default: random 64 chars
  # **********************
  # Environment Variables
  # **********************
  environments:
    debug: "clt:*"
    timeout: "90000"
    nodeEnv: "develop"
    # GraphQl mutation support
    graphqlMutationSupport: true
    # **********************
    # Internationalization
    # **********************
    locale: "fa"
    region: "IR"
    tz: "Asia/Tehran"
    # **********************
    # Messaging Config
    # **********************
    # Kavenegar
    kavenegar:
      apiKey: ""
      senders: ""
    # Melipayamak
    melipayamak:
      user: ""
      pass: ""
      from: ""
    # **********************
    # Client Config
    # **********************
    strictToken: true
    # Client
    uid: ""
    cid: ""
    appId: ""
    clientId: ""
    clientSecret: ""
    # Platform
    root:
      domain: "wenex.org"
      subject: "root@wenex.org"
    platformUrl: "http://platform-gateway.wenex-platform.svc.cluster.local"
    # Backend
    backend:
      authorizationCqrs: ""
    apiKey: ""
    # Frontend
    frontend:
      baseUrl: "https://platform.wenex.org"
      assetsUrl: "https://assets.wenex.org"
    # **********************
    # Logging Services
    # **********************
    # Sentry
    sentry:
      dsn: ""
      maxBreadcrumbs: "100"
      tracesSampleRate: "0.8"
    # **********************
    # Storage Services
    # **********************
    # Redis
    redis:
      host: "redis-stack-master.redis.svc.cluster.local"
      port: "6379"
      prefix: "clt"
      password: ""
    # Mongo
    mongo:
      host: "psmdb-server-psmdb-db-rs0.mongodb.svc.cluster.local"
      db: "wenex"
      prefix: "clt"
      user: "databaseAdmin"
      pass: ""
      query: "replicaSet=rs0&loadBalanced=true&authSource=admin"
    # **********************
    # Broker Services
    # **********************
    # Nats
    nats:
      user: "w3x"
      pass: "w3x"
      timeout: "90000"
      servers: "nats://nats.nats.svc.cluster.local:4222"
    # **********************
    # OAuth Information
    # **********************
    # Google
    google:
      client:
        id: ""
        secret: ""
        redirectUri: "https://platform.wenex.org/oauth"
    # **********************
    # Telemetry Services
    # **********************
    # OpenTelemetry
    otlp:
      port: "4318"
      host: "jaeger-instance-collector.opentelemetry.svc.cluster.local"
    # **********************
    # APM Service
    # **********************
    # Elastic APM
    apm:
      serverUrl: ""
      secretToken: ""
      verifyServerCert: "false"
    # **********************
    # Wenex Coworkers
    # **********************
    coworkers: [] # list of coworkers
  # **********************
  # Client Configuration
  # **********************
  configuration:
    services:
      host: client-services.wenex-client.svc.cluster.local
    workers:
      host: client-workers.wenex-client.svc.cluster.local
# **********************
# Client Backend
# **********************
assets:
  enabled: false
services:
  enabled: false
workers:
  enabled: false
# **********************
# Client Frontend
# **********************
frontend:
  enabled: false
  image:
    repository: vhidvz/client-frontend
    tag: "1.1.0"
  imagePullSecrets: []
