enabled: false

replicaCount: 3

image:
  repository: vhidvz/client-frontend
  pullPolicy: IfNotPresent
  tag: "1.1.0"

fullnameOverride: "client-frontend"

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false

autoscaling:
  enabled: false

environments:
  nuxt:
    # *****************************
    # Logging Services
    # *****************************
    sentry:
      url: ""
      authToken: ""
    # *****************************
    # Public Information
    # *****************************
    public:
      apiBaseUrl: "https://gateway.wenex.org/"
      # *****************************
      # Push Information
      # *****************************
      vapidPublicKey: ""
      # *****************************
      # Security Services
      # *****************************
      altcha:
        challengeUrl: "https://gateway.wenex.org/challenge"
      # *****************************
      # Client Information
      # *****************************
      appId: ""
      clientId: ""
      # MQTT Over WebSocket
      mqttWsUrl: "wss://emqx.wenex.org/mqtt"
      # *****************************
      # Logging Services
      # *****************************
      sentry:
        dsn: ""
        tracesSampleRate: "0.8"
      # *****************************
      # OAuth Information
      # *****************************
      # Google
      google:
        client:
          id: ""
          scope: "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
          redirectUri: "https://platform.wenex.org/oauth"