apiVersion: v1
kind: Secret
metadata:
  name: client-init-secrets
data:
  # LND Client
  INIT_LND_ROOT_PASSWORD: {{ .Values.global.secrets.init.lnd.rootPassword | default (randAlphaNum 40) | b64enc | quote }}
  INIT_LND_CLIENT_SECRET: {{ .Values.global.secrets.init.lnd.clientSecret | default (randAlphaNum 20 | sha256sum | trunc 40) | b64enc | quote }}
  # PHC Client
  INIT_PHC_ROOT_PASSWORD: {{ .Values.global.secrets.init.phc.rootPassword | default (randAlphaNum 40) | b64enc | quote }}
  INIT_PHC_CLIENT_SECRET: {{ .Values.global.secrets.init.phc.clientSecret | default (randAlphaNum 20 | sha256sum | trunc 40) | b64enc | quote }}
  # RSCH Client
  INIT_RSCH_ROOT_PASSWORD: {{ .Values.global.secrets.init.rsch.rootPassword | default (randAlphaNum 40) | b64enc | quote }}
  INIT_RSCH_CLIENT_SECRET: {{ .Values.global.secrets.init.rsch.clientSecret | default (randAlphaNum 20 | sha256sum | trunc 40) | b64enc | quote }}
  # COPD Client
  INIT_COPD_ROOT_PASSWORD: {{ .Values.global.secrets.init.copd.rootPassword | default (randAlphaNum 40) | b64enc | quote }}
  INIT_COPD_CLIENT_SECRET: {{ .Values.global.secrets.init.copd.clientSecret | default (randAlphaNum 20 | sha256sum | trunc 40) | b64enc | quote }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: client-secrets
data:
  AES_KEY: {{ .Values.global.secrets.aes | default (randAlphaNum 16 | sha256sum | trunc 64) | b64enc | quote }}
  HMAC_KEY: {{ .Values.global.secrets.altcha.hmacKey | default (randAlphaNum 16 | sha256sum | trunc 64) | b64enc | quote }}
type: Opaque
