apiVersion: v2
name: platform
description: A Helm chart for Kubernetes

type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: auth
    version: 1.0.0
    condition: auth.enabled
    repository: file://charts/auth

icon: https://artifacthub.io/image/8dee5d2f-5946-4fb5-b0a8-265ff014cdc1@1x
