replicaCount: 3

image:
  repository: wenex/platform
  pullPolicy: IfNotPresent
  tag: "1.0.0"

fullnameOverride: "platform-gateway"

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 80
  targetPort: 3010

ingress:
  enabled: false

autoscaling:
  enabled: false
