replicaCount: 2

fullnameOverride: "platform-gateway"

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 80
  targetPort: 3010

ingress:
  enabled: false

autoscaling:
  enabled: false

global:
  image:
    repository: wenex/platform
    pullPolicy: IfNotPresent
    tag: "1.0.0"

  secrets:
    init:
      rootPassword: "" # default: random 40 chars
      clientSecret: "" # default: random 40 chars
    aes: "" # default: random 64 chars
    jwt: "" # default: random 64 chars
    bcrypt: "" # default: random 32 chars

  environments:
    debug: "wnx:*"
    timeout: 90000
    nodeEnv: "develop"

    # **********************
    # Internationalization
    # **********************

    locale: "fa"
    region: "IR"
    tz: "Asia/Tehran"

    # **********************
    # Logging Services
    # **********************

    # Sentry
    sentry: {}

    # **********************
    # Storage Services
    # **********************

    # Redis
    redis:
      host: "redis-stack-master.redis.svc.cluster.local"
      port: 6379
      prefix: "wnx"
      password: "6Xu9rdP1g0267vDR5t6l4A2D9BYAMfUKimFCgBZr"

    # Minio
    minio:
      host: "minio.minio-tenant.svc.cluster.local"
      port: "80"
      accessKey: "uj8dDV7t29NGgFecY65Qpm"
      secretKey: "QLj9a3vdsUI5pbA8OleKyqNDnxzTC0G1ZoJm76FkH4WSVE"

    # Mongo
    mongo:
      host: "psmdb-server-psmdb-db-rs0.mongodb.svc.cluster.local"
      db: "wenex"
      prefix: "wnx"
      user: "databaseAdmin"
      pass: "5outyK4QIGPBE6pX2G"
      query: "replicaSet=rs0&authSource=admin"

    # ElasticSearch
    elasticsearch:
      prefix: "wnx"
      node: "https://elk-cluster-es-http.elastic-system.svc.cluster.local:9200"
      # apiKey: ""
      username: ""
      password: ""

    # **********************
    # Broker Services
    # **********************

    # Kafka
    kafka:
      host: "wenex-kafka-bootstrap.kafka.svc.cluster.local"
      port: 9092
      noPartitionerWarning: 1

    # EMQX
    emqx:
      username: "admin"
      password: "qHDZSxtyu7vWfc-YLGVCAMBU9E3NQr5Fn8_k2w6spaX!dj@4"
      exhookUrl: "http://platform-preserver.wenex-platform.svc.cluster.local:8080"
      baseUrl: "http://emqx-dashboard.emqx-operator-system.svc.cluster.local:18083/api/v5"

    # **********************
    # Telemetry Services
    # **********************

    # OpenTelemetry
    otlp: {}

    # **********************
    # APM Service
    # **********************

    # Elastic APM
    apm: {}

  configuration:
    auth:
      host: platform-auth.wenex-platform.svc.cluster.local
    domain:
      host: platform-domain.wenex-platform.svc.cluster.local
    context:
      host: platform-context.wenex-platform.svc.cluster.local
    essential:
      host: platform-essential.wenex-platform.svc.cluster.local
    financial:
      host: platform-financial.wenex-platform.svc.cluster.local
    general:
      host: platform-general.wenex-platform.svc.cluster.local
    identity:
      host: platform-identity.wenex-platform.svc.cluster.local
    special:
      host: platform-special.wenex-platform.svc.cluster.local
    touch:
      host: platform-touch.wenex-platform.svc.cluster.local
    content:
      host: platform-content.wenex-platform.svc.cluster.local

    watcher:
      host: platform-watcher.wenex-platform.svc.cluster.local
    observer:
      host: platform-observer.wenex-platform.svc.cluster.local
    preserver:
      host: platform-preserver.wenex-platform.svc.cluster.local
    dispatcher:
      host: platform-dispatcher.wenex-platform.svc.cluster.local

auth:
  enabled: false
domain:
  enabled: false
context:
  enabled: false
essential:
  enabled: false
financial:
  enabled: false
general:
  enabled: false
identity:
  enabled: false
special:
  enabled: false
touch:
  enabled: false
content:
  enabled: false

watcher:
  enabled: false
observer:
  enabled: false
preserver:
  enabled: false
dispatcher:
  enabled: false
