replicaCount: 3

fullnameOverride: "platform-gateway"

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 80
  targetPort: 3010

ingress:
  enabled: false

autoscaling:
  enabled: false

global:
  image:
    repository: wenex/platform
    pullPolicy: IfNotPresent
    tag: "1.0.0"

  config:
    debug: "wnx:*"
    timeout: 90000
    nodeEnv: "develop"

    # **********************
    # Internationalization
    # **********************

    locale: "fa"
    region: "IR"
    tz: "Asia/Tehran"

    # **********************
    # Storage Services
    # **********************

    # Redis
    redis:
      host: "redis-stack-master.redis.svc.cluster.local"
      port: 6379
      prefix: "wnx"
      password: "6Xu9rdP1g0267vDR5t6l4A2D9BYAMfUKimFCgBZr"
    
    # Minio
    minio:
      host: "minio.minio-tenant.svc.cluster.local"
      port: "80"
      accessKey: "uj8dDV7t29NGgFecY65Qpm"
      secretKey: "QLj9a3vdsUI5pbA8OleKyqNDnxzTC0G1ZoJm76FkH4WSVE"

    # Mongo
    mongo:
      host: "psmdb-server-psmdb-db-rs0.mongodb.svc.cluster.local"
      db: "wenex"
      prefix: "wnx"
      user: "databaseAdmin"
      pass: "5outyK4QIGPBE6pX2G"
      query: "replicaSet=rs0&authSource=admin"

    # **********************
    # Broker Services
    # **********************

    # Kafka
    kafka:
      host: "wenex-kafka-bootstrap.kafka.svc.cluster.local"
      port: 9092
    
    # EMQX
    emqx:
      username: "admin"
      password: "qHDZSxtyu7vWfc-YLGVCAMBU9E3NQr5Fn8_k2w6spaX!dj@4"
      exhookUrl: "http://platform-preserver.wenex-platform.svc.cluster.local:6030"
      baseUrl: "http://emqx-dashboard.emqx-operator-system.svc.cluster.local:18083/api/v5"
  
  services:
    auth:
      host: platform-auth.wenex-platform.svc.cluster.local

auth:
  enabled: false
