apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform.fullname" . }}-init-secrets
data:
  ROOT_PASSWORD: {{ .Values.global.secrets.init.rootPassword | default (randAlphaNum 40) | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.global.secrets.init.clientSecret | default (randAlphaNum 20 | sha256sum | trunc 40) | b64enc | quote }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform.fullname" . }}-secrets
data:
  AES_SECRET: {{ .Values.global.secrets.aes | default (randAlphaNum 16 | sha256sum | trunc 64) | b64enc | quote }}
  JWT_SECRET: {{ .Values.global.secrets.jwt | default (randAlphaNum 64) | b64enc | quote }}
  BCRYPT_SALT: {{ .Values.global.secrets.bcrypt | default (randAlphaNum 8 | sha256sum | trunc 32) | b64enc | quote }}
type: Opaque
