apiVersion: v1
kind: Secret
metadata:
  name: credential
data:
  ADMIN_USERNAME: {{ .Values.global.secrets.adminUsername | default (randAlphaNum 40) | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.global.secrets.adminPassword | default (randAlphaNum 40) | b64enc | quote }}
type: Opaque
