apiVersion: v1
kind: Service
metadata:
  name: {{ include "watcher.fullname" . }}
  labels:
    {{- include "watcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "watcher.selectorLabels" . | nindent 4 }}
